# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
    - { resource: services/bus.yaml }
    - { resource: services/api.yaml }
    - { resource: services/repositories.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    
    App\Apps\Api\:
        resource: '../src/Apps/Api/*'
        tags: [ 'controller.service_arguments' ]
    
    App\:
        resource: '../src/'
        
    Shared\:
        resource: '../shared/'
        
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #handlers
    _instanceof:
        Shared\Infrastructure\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
        
        Shared\Infrastructure\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        
        Shared\Infrastructure\Bus\Event\DomainEventSubscriber:
            tags:
                - { name: messenger.message_subscriber, bus: event.bus }

        Shared\Infrastructure\Request\RequestInterface:
            public: true

